# Reference: https://github.com/i3/i3/blob/next/etc/config

after-startup-command = ['exec-and-forget borders active_color=gradient(top_right=0xFF8752A3,botton_left=0xFF6274E7) inactive_color=0x00000000 width=7.0']

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
	inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

[mode.main.binding]
	# Application mappings
    alt-t = 'exec-and-forget open -n -a "iTerm"'
	alt-b = 'exec-and-forget open -n -a "Google Chrome" --args --profile-directory=Default'
	alt-shift-b = 'exec-and-forget open -n -a "Google Chrome" --args --profile-directory="Profile 1"'

    # i3 wraps focus by default
    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-y = 'join-with left'
    alt-u = 'join-with down'
    alt-i = 'join-with up'
    alt-o = 'join-with right'

    alt-f = 'fullscreen'
    alt-enter = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']

    alt-shift-r = 'reload-config'
    alt-r = 'mode resize'
	
	# Disable "hide" windows
	cmd-h = []
	cmd-alt-h = []

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

# App overrides
[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.gimp.gimp-2.10'
run = ['layout floating']
